// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

type Env struct {
	EnvID      int64
	Name       string
	Comment    string
	CreateTime string
	UpdateTime string
	Enabled    int64
}

type Var struct {
	VarID      int64
	EnvID      int64
	Name       string
	Comment    string
	CreateTime string
	UpdateTime string
	Value      string
	Enabled    int64
}

type VarRef struct {
	VarRefID   int64
	EnvID      int64
	Name       string
	Comment    string
	CreateTime string
	UpdateTime string
	VarID      int64
	Enabled    int64
}

type VwEnvExportable struct {
	EnvID      int64
	EnvName    string
	Name       string
	Type       string
	Comment    string
	Enabled    int64
	Value      string
	CreateTime string
	UpdateTime string
}

type VwEnvVarVarRefUniqueName struct {
	EnvID int64
	Name  string
}

type VwVarExpanded struct {
	VarID      int64
	EnvID      int64
	EnvName    string
	Name       string
	Value      string
	Comment    string
	CreateTime string
	UpdateTime string
}

type VwVarRefExpanded struct {
	VarRefID   int64
	EnvID      int64
	EnvName    string
	Name       string
	VarID      int64
	RefVarName string
	RefEnvName string
	Comment    string
	CreateTime string
	UpdateTime string
}
