// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vw_env_exportable.sql

package sqlcgen

import (
	"context"
)

const envExportableList = `-- name: EnvExportableList :many
SELECT name, enabled, value FROM vw_env_exportable
WHERE env_id = ?
ORDER BY type ASC, name ASC
`

type EnvExportableListRow struct {
	Name    string
	Enabled int64
	Value   string
}

func (q *Queries) EnvExportableList(ctx context.Context, envID int64) ([]EnvExportableListRow, error) {
	rows, err := q.db.QueryContext(ctx, envExportableList, envID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EnvExportableListRow
	for rows.Next() {
		var i EnvExportableListRow
		if err := rows.Scan(&i.Name, &i.Enabled, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
